flags: {}
packages:
- '.'
- '../gl-pal2'
- '../Thop/modules/glfw-pal'
- '../Thop/modules/hydra-hs'
- '../Thop/modules/oculus-mini'
extra-deps:
- GLFW-b-1.4.7.2
- bindings-GLFW-3.1.1.3
resolver: nightly-2015-06-28
